### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by alzpublic** [wasienv/wasienv#3]
I've tried to compile a simple "hello world" demo. The compiler fails with the next error:

```
 wasic++ main.cpp -o main                                                                                                                                                                              
Traceback (most recent call last):
  File "...../wasienv/env/bin/wasic++", line 11, in <module>
    load_entry_point('wasienv==0.2.2', 'console_scripts', 'wasic++')()
  File "...../wasienv/env/lib/python3.7/site-packages/wasienv/tools.py", line 168, in wrapped_f
    sys.exit(f(sys.argv))
  File "...../wasienv/env/lib/python3.7/site-packages/wasienv/wasicc.py", line 43, in run
    try_to_wrap_executable(target)
  File "...../wasienv/env/lib/python3.7/site-packages/wasienv/tools.py", line 101, in try_to_wrap_executable
    first_bytes = f.read(4)
  File "/usr/local/bin/../Cellar/python/3.7.4_1/bin/../Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 85: invalid start byte
```

**Comment by syrusakbary** [comment]
@alzpublic thanks for the report!
If you could provide some more info about your system it will be super useful for debugging and fixing the issue.

What version of Python are you using? (2, 3?) What is your platform? (Linux, macOS?)
> Note: You can get those easily with: `uname -v && python -V`

**Comment by alzpublic** [comment]
OSX

```
python --version                                                                                                                                                                                       
Python 3.7.4
```

**Comment by syrusakbary** [comment]
Thanks for the report!

The issue is now fixed on master. I also published a new version of `wasienv`.

You can try re-installing it (by running the install script):
```sh
curl https://raw.githubusercontent.com/wasienv/wasienv/master/install.sh | sh
```

Let me know if it solved the issue :)

**Comment by alzpublic** [comment]
confirmed :)
