### ISSUE TITLE
cmake simple project not working: used wasimake

### ISSUE THREAD

**Issue by anuragvohraec** [wasienv/wasienv#46]
Hi All,

I have been trying to test wasimake to compile a CMAKE project.
It has juts two files:
1. ` async_test.cpp`
2. `CMakeLists.txt`

```c++
#include <iostream>
#include <string>
#include <chrono>
#include <thread>
#include <future>

using namespace std::chrono;

std::string fetchDataFromDB(std::string recvdData){
    std::this_thread::sleep_for(seconds(5));

    return "DB_"+recvdData;
}

std::string fetchDataFromFile(std::string recvdData){
    std::this_thread::sleep_for(seconds(5));
    return "File_"+recvdData;
}

int main(int, char**) {
    std::cout << "App Started" << std::endl;

    auto start = system_clock::now();
    auto getFromDB = std::async(std::launch::async,fetchDataFromDB,"Data1");
    auto getFromFile = std::async(std::launch::async,fetchDataFromFile,"Data2");

    auto dataFromDB = getFromDB.get();
    auto dataFromFile = getFromFile.get();
    
    auto end = system_clock::now();
    auto diff = duration_cast<seconds>(end-start).count();
    
    std::cout << "Total time taken ="<<diff <<" Seconds" << std::endl;
    std::cout << dataFromDB +" "+dataFromFile << std::endl;

    return 0;
}
```

```
cmake_minimum_required(VERSION 3.0.0)
project(asyn_test VERSION 0.1.0)

include(CTest)
enable_testing()

add_executable(asyn_test main.cpp)

target_link_libraries(${PROJECT_NAME} pthread)

set(CPACK_PROJECT_NAME ${PROJECT_NAME})
set(CPACK_PROJECT_VERSION ${PROJECT_VERSION})
include(CPack)
```
I create the build folder and then `cd` into it and run `wasimake cmake ../` from it.
Now when I run this, it gives me these errors:

```
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Check for working C compiler: /home/anurag/.wasienv/bin/wasicc
-- Check for working C compiler: /home/anurag/.wasienv/bin/wasicc -- broken
CMake Error at /usr/share/cmake-3.13/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/home/anurag/.wasienv/bin/wasicc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/anurag/ws/cpp/async_test/test1/build/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/make" "cmTC_bcfdf/fast"
    /usr/bin/make -f CMakeFiles/cmTC_bcfdf.dir/build.make CMakeFiles/cmTC_bcfdf.dir/build
    make[1]: Entering directory '/home/anurag/ws/cpp/async_test/test1/build/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_bcfdf.dir/testCCompiler.c.obj
    /home/anurag/.wasienv/bin/wasicc    -o CMakeFiles/cmTC_bcfdf.dir/testCCompiler.c.obj   -c /home/anurag/ws/cpp/async_test/test1/build/CMakeFiles/CMakeTmp/testCCompiler.c
    Traceback (most recent call last):
      File "/home/anurag/.wasienv/bin/wasicc", line 10, in <module>
        sys.exit(wasicc())
      File "/home/anurag/.local/lib/python2.7/site-packages/wasienv/commands.py", line 20, in wasicc
        return execute(wasicc_run)
      File "/home/anurag/.local/lib/python2.7/site-packages/wasienv/tools.py", line 196, in execute
        sys.exit(f(args))
      File "/home/anurag/.local/lib/python2.7/site-packages/wasienv/wasicc.py", line 14, in run
        check_program(main_program)
      File "/home/anurag/.local/lib/python2.7/site-packages/wasienv/tools.py", line 61, in check_program
        raise Exception("The program {} was not found. Is the SDK installed?\nYou can install it via: wasienv install-sdk unstable".format(os.path.basename(cmd)))
    Exception: The program clang was not found. Is the SDK installed?
    You can install it via: wasienv install-sdk unstable
    make[1]: *** [CMakeFiles/cmTC_bcfdf.dir/build.make:66: CMakeFiles/cmTC_bcfdf.dir/testCCompiler.c.obj] Error 1
    make[1]: Leaving directory '/home/anurag/ws/cpp/async_test/test1/build/CMakeFiles/CMakeTmp'
    make: *** [Makefile:121: cmTC_bcfdf/fast] Error 2
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!
See also "/home/anurag/ws/cpp/async_test/test1/build/CMakeFiles/CMakeOutput.log".
See also "/home/anurag/ws/cpp/async_test/test1/build/CMakeFiles/CMakeError.log".
```

Tried even
```
wasienv install-sdk unstable
Output: The SDK 8 is already installed
```

How to solve this ?

**Comment by anuragvohraec** [comment]
Tried even the docker image
`docker run --rm -v `pwd`:`pwd` wasienv/wasienv wasimake cmake `pwd``
Got response:
```
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
See also "//CMakeFiles/CMakeOutput.log".
```

**Comment by anuragvohraec** [comment]
Problem with even using docker:
```
docker run --rm -v `pwd`:`pwd` wasienv/wasienv wasimake cmake `pwd`
```

Error on docker:
```
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
See also "//CMakeFiles/CMakeOutput.log".
```

**Comment by anuragvohraec** [comment]
So for some reason if we dowload using the wasi sdk using `wasienv install-sdk 8` , it will not have a `clang++` in it.
So download WASI_SDK 8 from there release page and manually untar it in the wasi home `bin` folder.

Although my code is still not working as WASI-SDK do not supports thread at the moment.
Do any one has any hack on how to run a multithreaded WASM code ?

**Comment by sfranzyshen** [comment]
This is still a problem ... no matter what wasi-sdk is installed ... I also tried downloading from the release page and manually installing it as mentioned above ... but still have the same result 

```
name@DESKTOP-G3DFJ6S:/mnt/d/WASM$ wasienv default-sdk 10
name@DESKTOP-G3DFJ6S:/mnt/d/WASM$ wasimake cmake --system-information
CMake Error at /usr/share/cmake-3.21/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "/home/name/.local/bin/wasicc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /mnt/d/WASM/__cmake_systeminformation/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/make -f Makefile cmTC_6a372/fast && /usr/bin/make  -f CMakeFiles/cmTC_6a372.dir/build.make CMakeFiles/cmTC_6a372.dir/build
    make[1]: Entering directory '/mnt/d/WASM/__cmake_systeminformation/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_6a372.dir/testCCompiler.c.o
    /home/name/.local/bin/wasicc    -MD -MT CMakeFiles/cmTC_6a372.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_6a372.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_6a372.dir/testCCompiler.c.o -c /mnt/d/WASM/__cmake_systeminformation/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_6a372
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_6a372.dir/link.txt --verbose=1
    /home/name/.local/bin/wasicc CMakeFiles/cmTC_6a372.dir/testCCompiler.c.o -o cmTC_6a372
    wasm-ld: error: unknown file type: CMakeFiles/cmTC_6a372.dir/testCCompiler.c.o
    clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
    CMakeFiles/cmTC_6a372.dir/build.make:99: recipe for target 'cmTC_6a372' failed
    make[1]: *** [cmTC_6a372] Error 1
    make[1]: Leaving directory '/mnt/d/WASM/__cmake_systeminformation/CMakeFiles/CMakeTmp'
    Makefile:127: recipe for target 'cmTC_6a372/fast' failed
    make: *** [cmTC_6a372/fast] Error 2


  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:6 (project)


Error: --system-information failed on internal CMake!
name@DESKTOP-G3DFJ6S:/mnt/d/WASM$ wasienv install-sdk 7
name@DESKTOP-G3DFJ6S:/mnt/d/WASM$ wasienv default-sdk 7
name@DESKTOP-G3DFJ6S:/mnt/d/WASM$ wasimake cmake --system-information
CMake Error at /usr/share/cmake-3.21/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "/home/name/.local/bin/wasicc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /mnt/d/WASM/__cmake_systeminformation/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/make -f Makefile cmTC_0cc13/fast && /usr/bin/make  -f CMakeFiles/cmTC_0cc13.dir/build.make CMakeFiles/cmTC_0cc13.dir/build
    make[1]: Entering directory '/mnt/d/WASM/__cmake_systeminformation/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_0cc13.dir/testCCompiler.c.o
    /home/name/.local/bin/wasicc    -MD -MT CMakeFiles/cmTC_0cc13.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_0cc13.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_0cc13.dir/testCCompiler.c.o -c /mnt/d/WASM/__cmake_systeminformation/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_0cc13
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_0cc13.dir/link.txt --verbose=1
    /home/name/.local/bin/wasicc CMakeFiles/cmTC_0cc13.dir/testCCompiler.c.o -o cmTC_0cc13
    wasm-ld: error: unknown file type: CMakeFiles/cmTC_0cc13.dir/testCCompiler.c.o
    clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
    CMakeFiles/cmTC_0cc13.dir/build.make:99: recipe for target 'cmTC_0cc13' failed
    make[1]: *** [cmTC_0cc13] Error 1
    make[1]: Leaving directory '/mnt/d/WASM/__cmake_systeminformation/CMakeFiles/CMakeTmp'
    Makefile:127: recipe for target 'cmTC_0cc13/fast' failed
    make: *** [cmTC_0cc13/fast] Error 2


  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:6 (project)

Error: --system-information failed on internal CMake!
name@DESKTOP-G3DFJ6S:/mnt/d/WASM$
```

**Comment by sfranzyshen** [comment]
Same thing happened in the docker container ... 
# wasimake doesn't work !!

```
name@:/mnt/d/$docker run -v `pwd`:`pwd` -it wasienv/wasienv bash

root@6347e6388120:/# cmake --version
cmake version 3.17.1

root@6347e6388120:/# wasimake cmake --system-information
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.

root@6347e6388120:/mnt/d/WASM/binaryen-version_101/build# apt install make
Reading package lists... Done

root@6347e6388120:/mnt/d/WASM/binaryen-version_101/build# make --version
GNU Make 4.2.1

root@6347e6388120:/mnt/d/WASM/binaryen-version_101/build# wasienv install-sdk unstable
The SDK 8 is already installed

root@6347e6388120:/mnt/d/WASM# wasimake cmake --system-information
CMake Error at /opt/cmake/share/cmake-3.17/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/root/.wasienv/bin/wasicc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /mnt/d/WASM/__cmake_systeminformation/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/make cmTC_25876/fast && /usr/bin/make  -f CMakeFiles/cmTC_25876.dir/build.make CMakeFiles/cmTC_25876.dir/build
    make[1]: Entering directory '/mnt/d/WASM/__cmake_systeminformation/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_25876.dir/testCCompiler.c.o
    /root/.wasienv/bin/wasicc    -o CMakeFiles/cmTC_25876.dir/testCCompiler.c.o   -c /mnt/d/WASM/__cmake_systeminformation/CMakeFiles/CMakeTmp/testCCompiler.c
    In file included from <built-in>:1:
    /root/.local/lib/python2.7/site-packages/wasienv/stubs/preamble.h:30:9: warning: 'ESHUTDOWN' macro redefined [-Wmacro-redefined]
    #define ESHUTDOWN 0
            ^
    /root/.local/lib/python2.7/site-packages/wasienv/stubs/preamble.h:28:9: note: previous definition is here
    #define ESHUTDOWN 1
            ^
    /root/.local/lib/python2.7/site-packages/wasienv/stubs/preamble.h:116:62: warning: declaration of 'struct sigaction' will not be visible outside of this function [-Wvisibility]
    __attribute__((weak)) int sigaction(int signum, const struct sigaction *act,
                                                                 ^
    /root/.local/lib/python2.7/site-packages/wasienv/stubs/preamble.h:125:1: warning: control reaches end of non-void function [-Wreturn-type]
    }
    ^
    /root/.local/lib/python2.7/site-packages/wasienv/stubs/preamble.h:134:1: warning: control reaches end of non-void function [-Wreturn-type]
    }
    ^
    /root/.local/lib/python2.7/site-packages/wasienv/stubs/preamble.h:138:1: warning: control reaches end of non-void function [-Wreturn-type]
    }
    ^
    5 warnings generated.
    Linking C executable cmTC_25876
    /opt/cmake/bin/cmake -E cmake_link_script CMakeFiles/cmTC_25876.dir/link.txt --verbose=1
    /root/.wasienv/bin/wasicc      CMakeFiles/cmTC_25876.dir/testCCompiler.c.o  -o cmTC_25876
    wasm-ld: error: unknown file type: CMakeFiles/cmTC_25876.dir/testCCompiler.c.o
    clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [CMakeFiles/cmTC_25876.dir/build.make:107: cmTC_25876] Error 1
    make[1]: Leaving directory '/mnt/d/WASM/__cmake_systeminformation/CMakeFiles/CMakeTmp'
    make: *** [Makefile:141: cmTC_25876/fast] Error 2

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:6 (project)

Error: --system-information failed on internal CMake!

```

**Comment by sfranzyshen** [comment]
* I started off with a fresh Ubuntu 20.04.2 LTS install ...
* successfully installed wasienv using the [install script](https://github.com/wasienv/wasienv#install)
* successfully performed `wasimake cmake --system-information` without errors
* successfully performed `wasimake cmake -DBUILD_TESTS=OFF ..` from the build folder of a project (wabt) 
* successfully performed `wasimake make wasm-strip` and produced a functioning wasm file

So, I guess the status of the build platform has a lot to do with having success with the wasienv project.

### This problem resurfaced when changing to sdk 12 (10 & 11 work). It Appears to be linked to changes with clang-11 and up ...

```
name@DESKTOP-G3DFJ6S:~/binaryen-version_101/build$ wasimake cmake -DBUILD_TESTS=OFF ..
-- The C compiler identification is Clang 11.0.0
-- The CXX compiler identification is Clang 11.0.0
-- Check for working C compiler: /home/name/.wasienv/bin/wasicc
-- Check for working C compiler: /home/name/.wasienv/bin/wasicc -- broken
CMake Error at /usr/share/cmake-3.16/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/home/name/.wasienv/bin/wasicc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/name/binaryen-version_101/build/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/make cmTC_f2d78/fast && /usr/bin/make -f CMakeFiles/cmTC_f2d78.dir/build.make CMakeFiles/cmTC_f2d78.dir/build
    make[1]: Entering directory '/home/name/binaryen-version_101/build/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_f2d78.dir/testCCompiler.c.obj
    /home/name/.wasienv/bin/wasicc    -o CMakeFiles/cmTC_f2d78.dir/testCCompiler.c.obj   -c /home/name/binaryen-version_101/build/CMakeFiles/CMakeTmp/testCCompiler.c
    In file included from <built-in>:1:
    /home/name/.local/lib/python3.8/site-packages/wasienv/stubs/preamble.h:115:62: warning: declaration of 'struct sigaction' will not be visible outside of this function [-Wvisibility]
    __attribute__((weak)) int sigaction(int signum, const struct sigaction *act,
                                                                 ^
    1 warning generated.
    Linking C executable cmTC_f2d78
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_f2d78.dir/link.txt --verbose=1
    /home/name/.wasienv/bin/wasicc    -Wl,--no-threads  CMakeFiles/cmTC_f2d78.dir/testCCompiler.c.obj  -o cmTC_f2d78
    wasm-ld: error: unknown argument: --no-threads
    clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [CMakeFiles/cmTC_f2d78.dir/build.make:87: cmTC_f2d78] Error 1
    make[1]: Leaving directory '/home/name/binaryen-version_101/build/CMakeFiles/CMakeTmp'
    make: *** [Makefile:121: cmTC_f2d78/fast] Error 2





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)


-- Configuring incomplete, errors occurred!
See also "/home/name/binaryen-version_101/build/CMakeFiles/CMakeOutput.log".
See also "/home/name/binaryen-version_101/build/CMakeFiles/CMakeError.log".
```

**Comment by sfranzyshen** [comment]
the problem with the differences between clang-10 and the higher clangs seems to be linked to Ubuntu missing system dependency libtinfo.so.5 ... 
```
name@DESKTOP-G3DFJ6S:/mnt/d/WASM/tar-1.34$ wasicc --help
/home/name/.local/lib/python3.8/site-packages/wasienv-storage/sdks/11/wasi-sdk-11.0/bin/clang: error while loading shared libraries:
libtinfo.so.5: cannot open shared object file: No such file or directory
```
the solution is to install it ...

`sudo apt install libtinfo5`
