### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by fgsch** [wasienv/wasienv#5]
`$ wasicc a.c -o foo`

Errors with:

```
In file included from <built-in>:1:
/usr/local/lib/python2.7/dist-packages/wasienv/stubs/preamble.h:40:62: warning: declaration of 'struct sigaction' will not be visible outside of this function [-Wvisibility]
__attribute__((weak)) int sigaction(int signum, const struct sigaction *act,
                                                             ^
1 warning generated.
Traceback (most recent call last):
  File "/usr/local/bin/wasicc", line 11, in <module>
    sys.exit(wasicc())
  File "/usr/local/lib/python2.7/dist-packages/wasienv/commands.py", line 18, in wasicc
    return execute(wasicc_run)
  File "/usr/local/lib/python2.7/dist-packages/wasienv/tools.py", line 172, in execute
    sys.exit(f(sys.argv))
  File "/usr/local/lib/python2.7/dist-packages/wasienv/wasicc.py", line 42, in run
    try_to_wrap_executable(target)
  File "/usr/local/lib/python2.7/dist-packages/wasienv/tools.py", line 124, in try_to_wrap_executable
    shutil.copy(new_target_path, temp_target_path)
  File "/usr/lib/python2.7/shutil.py", line 133, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    raise Error("`%s` and `%s` are the same file" % (src, dst))
shutil.Error: `/tmp/foo.wasm` and `/tmp/foo.wasm` are the same file
```

Version: wasienv (0.3.1)
OS: Ubuntu 18.04.3

**Comment by syrusakbary** [comment]
Hi @fgsch  can you post the code for the file `a.c`?

It will help for trying to reproduce the issue :)

**Comment by fgsch** [comment]
Sure:

```
#include <stdio.h>

int main(int argc, char **argv)
{
    if (argc < 2) {
        printf("Hello, WASI!\n");
    } else {
        printf("Hello, %s!\n", argv[1]);
    }
}
```

**Comment by fgsch** [comment]
FWIW, simply running `wasicc a.c` works but only generates the wasm file named `a.out`:
```
$ wasicc a.c
In file included from <built-in>:1:
/usr/local/lib/python2.7/dist-packages/wasienv/stubs/preamble.h:40:62: warning: declaration of 'struct sigaction' will not be visible outside of this function [-Wvisibility]
__attribute__((weak)) int sigaction(int signum, const struct sigaction *act,
                                                             ^
1 warning generated.
```

**Comment by fgsch** [comment]
Ok, I just looked at the code and I realised I didn't mention a minor detail that is causing this... the file lives in `/tmp`.

I was testing `wasicc` with some basic code (as you can see from above) and I put the file under that directory so this obviously fails:

```
    temp_target_path = os.path.join('/tmp', os.path.split(new_target_path)[1])
    shutil.copy(new_target_path, temp_target_path)
```

Because the file is already in `/tmp`.
